general = {disable_mod = false, auto_start = false, space_modules = true, shadow_text = true, animations = false, animationSpeed = 1.0, fontScale = 1.0, background_color = 1867534416, hide_debug_crosshair = false, hide_sidebar = true, hide_bossbar = true, always_show_profiler = true, always_show_tps = false, always_show_ping = true}
[[modules_left]]
	name = "minecraft"
	name_color = 10506797
	value_color = 43520
	enabled = true
	lines = {minecraft = true}
[[modules_left]]
	name = "coords"
	name_color = 16733525
	color_x = 16733525
	color_y = 5635925
	color_z = 5636095
	enabled = true
	lines = {player_coords = true, block_coords = true, chunk_relative_coords = true, chunk_coords = true, velocity = true, absolute_velocity = true, horizontal_velocity = true}
[[modules_left]]
	name = "location"
	name_color = 43520
	value_color = 5636095
	enabled = true
	lines = {dimension = true, facing = true, rotation = true, light = true, light_server = true, highest_block = true, highest_block_server = true, biome = true, local_difficulty = true, day_ticks = true, days_played = true, slime_chunk = true}

[[modules_right]]
	name = "fps"
	color_high = 5635925
	color_med = 16777045
	color_low = 16733525
	enabled = true
	lines = {fps = true}
[[modules_right]]
	name = "system"
	name_color = 16755200
	value_color = 5636095
	enabled = true
	lines = {time = true, java_version = true, memory_usage = true, allocation_rate = true, allocated_memory = true, cpu = true, display = true, gpu = true, gpu_utilization = true, opengl_version = true, gpu_driver = true}
[[modules_right]]
	name = "server"
	name_color = 11184810
	value_color = 16777045
	enabled = true
	lines = {server_tick = true, packets_sent = true, packets_received = true, tick_manager_status = true}
