name = "Minecraft Threeie"
author = "itsmetrevor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c7d9913d3596a3199ac7b12c6c1099c1ab602f096a3a2388c4936e5cc594e98"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
