name = "Minecraft Threeie"
author = "itsmetrevor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "247fc6554f9738f5886cca6d8276a38cf5aea563b64abccdb6da9f936c8567a8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
