name = "Minecraft Threeie"
author = "itsmetrevor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "576fa26a9205c4791d58e698af79a32d6c73d0163ead755466e8bb1705a7fbc6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
