name = "Minecraft Threeie"
author = "itsmetrevor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50042557507cceed72aeb3e4b7245a5623f2f836d44d8766b6daa6521d7020b1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
