name = "Minecraft Threeie"
author = "itsmetrevor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cee6f4ea27c9caa69100377f9af8248badc5afc4584795b49538b39a9ec1b7d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
