name = "Minecraft Threeie"
author = "itsmetrevor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2aff665c10cb8663d36e00eed4372265548f9634eb29696455a924b19fa364c1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
