name = "Minecraft Threeie"
author = "itsmetrevor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97a9cd5d23bb647c1323a972c199b7172e94e63f905d6b212bf2def461f5bb28"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
