name = "Minecraft Threeie"
author = "itsmetrevor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88665dd868f3b752e5f0aeacc424300b04f66ae3bd7c82471d8a013941af893d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
