name = "Minecraft Threeie"
author = "itsmetrevor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98dd40f48ac160191aafca26b51bb548da21fc49e938396494904e65889eb8ac"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
